name: ugao
description: A game changer in the agriculture industry.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  page_transition: ^1.1.4
  simple_animations: ^1.3.3
  rxdart: 0.22.2
  transparent_image: 1.0.0
  grouped_buttons: ^1.0.4
  provider: ^4.3.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  firebase_storage: ^3.1.6
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.3.2
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: any
  flutter_rating_bar: ^1.3.0+1
  intl: any
  numberpicker: ^1.0.0
  flare_splash_screen: ^2.1.2
  image_picker: ^0.6.2+3
  rflutter_alert: ^1.0.3
  argon_buttons_flutter: ^1.0.2
  flutter_spinkit: ^4.1.2
  intl_phone_field: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
